### ISSUE TITLE
Crashes on webpack 4.x

### ISSUE THREAD

**Issue by eramdam** [johnnyreilly/fork-ts-checker-notifier-webpack-plugin#2]
When trying to use the plugin in its `0.4.0` version with webpack 4, it crashes with the following stack

```
/Users/damien/Documents/Git/WRK/front-client/node_modules/fork-ts-checker-notifier-webpack-plugin/index.js:46
      return diagnostic.isErrorSeverity();
                        ^

TypeError: Cannot read property 'isErrorSeverity' of undefined
    at /Users/damien/Documents/Git/WRK/front-client/node_modules/fork-ts-checker-notifier-webpack-plugin/index.js:46:25
    at Array.find (native)
    at module.exports.ForkTsCheckerNotifierWebpackPlugin.buildNotification (/Users/damien/Documents/Git/WRK/front-client/node_modules/fork-ts-checker-notifier-webpack-plugin/index.js:45:41)
    at module.exports.ForkTsCheckerNotifierWebpackPlugin.compilationDone (/Users/damien/Documents/Git/WRK/front-client/node_modules/fork-ts-checker-notifier-webpack-plugin/index.js:90:27)
    at SyncHook.eval [as call] (eval at create (/Users/damien/Documents/Git/WRK/front-client/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:7:1)
    at SyncHook.lazyCompileHook [as _call] (/Users/damien/Documents/Git/WRK/front-client/node_modules/tapable/lib/Hook.js:35:21)
    at ForkTsCheckerWebpackPlugin.handleServiceMessage (/Users/damien/Documents/Git/WRK/front-client/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:424:54)
    at ChildProcess.<anonymous> (/Users/damien/Documents/Git/WRK/front-client/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:382:70)
    at ChildProcess.emit (events.js:160:13)
    at emit (internal/child_process.js:790:12)
```

From what I could see by adding logs to the file directly, it seems like [this method](https://github.com/johnnyreilly/fork-ts-checker-notifier-webpack-plugin/blob/master/index.js#L86) receives `undefined, undefined` as its argument, making everything crash down the line. 

Downgrading to `0.2.0` "fixes" the crashes but no notifications are displayed at all so it kinda defeats the purpose.

Glad to provide more informations if needed.

**Comment by johnnyreilly** [comment]
Yup - I think that this fix is required in fork-ts-checker-webpack-plugin: https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/104

This has been merged but not yet shipped. Do you want to clone fork-ts-checker-webpack-plugin, build it and test it to confirm if that's correct?

If so then I might put out a release of the fork-ts-checker-webpack-plugin on the unofficial alpha channel: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin

**Comment by eramdam** [comment]
@johnnyreilly it works. I used `yarn link` to use a local built version of `fork-ts-checker-webpack-plugin` to test and the notifications work 👍

**Comment by johnnyreilly** [comment]
Hey @eramdam, thanks for the test!  I've published a new release of the fork-ts-checker-webpack-plugin on the unofficial alpha channel: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin which people can use until fork-ts-checker-webpack-plugin ships next time.

I'll leave this issue open as an aide memoire in the mean time.

**Comment by developer-lindner** [comment]
Works with alpha version, but the order seems to be crucial:

new ForkTsCheckerWebpackPlugin(),
new ForkTsCheckerNotifierWebpackPlugin(),

**Comment by johnnyreilly** [comment]
Cool - that may be a requirement of the new webpack plugin approach. Would you like to submit a docs PR stating that so others don't get stuck on this?

**Comment by developer-lindner** [comment]
@johnnyreilly with tslint: true in configuration of ForkTsCheckerWebpackPlugin any notification will be disabled?! sad :/

**Comment by johnnyreilly** [comment]
In what way? Notification doesn't happen if tslint is in play? Could you sling some `console.log`s in your local build and discover if it's not being handled correctly upon receipt or whether it's not arriving at all? I'd really appreciate it if you could put some time into this. My new application is going live right now so I'm fairly occupied... Happy to advise though!
