### ISSUE TITLE
Build error on M3 Mac - Error: spawn Unknown system error -86

### ISSUE THREAD

**Issue by sjclemmy** [johnnyreilly/fork-ts-checker-notifier-webpack-plugin#73]
I've not looked into this - just thought you might want to know that there might be a problem with M3 - might be my setup as I'm new to the repo I'm working on, but also might be something to do with M3. If I work it out I'll update.

### Expected Behaviour
It builds

### Actual Behaviour
Throws this:
```
node:internal/child_process:421
    throw new ErrnoException(err, 'spawn');
          ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at Object.execFile (node:child_process:351:17)
    at module.exports.fileCommandJson (.../node_modules/node-notifier/lib/utils.js:88:13)
    at NotificationCenter.notifyRaw (.../node_modules/node-notifier/notifiers/notificationcenter.js:81:11)
    at ForkTsCheckerNotifierWebpackPlugin.compilationDone (.../node_modules/fork-ts-checker-notifier-webpack-plugin/index.js:14:41)
    at Hook.eval [as call] (eval at create (.../node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at Hook.CALL_DELEGATE [as _call] (.../node_modules/tapable/lib/Hook.js:14:14)
    at .../node_modules/fork-ts-checker-webpack-plugin/lib/hooks/tap-done-to-async-get-issues.js:58:31
    at Generator.next (<anonymous>) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}

Node.js v22.0.0
error Command failed with exit code 1.
```

### Steps to Reproduce the Problem
Add this plugin along with `ForkTsCheckerWebpackPlugin`

### Location of a Minimal Repository that Demonstrates the Issue.
n/a

**Comment by ShlomiL4** [comment]
@sjclemmy Have you found a solution to this issue? 
we are encountering it as well on some of our M3 macs

**Comment by andmev** [comment]
@sjclemmy , @ShlomiL4 #77
